libmilter might need libpthread
when libmilter needs -pthread, ./configure failed with:

```
/usr/bin/ld: /usr/lib/libmilter.a(signal.o): undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
```